# .github/workflows/manual-trigger.yml

name: Manual Trigger Example
on:
 push:
  branches: main

jobs:
  random-failure:
   runs-on: ubuntu-latest
   steps:
    - name: generate random number
      id: generate_number
      run: echo " random_number=$(($RANDOM % 2))" >> GITHUB_OUTPUT
    - name: pass or faile
      run: if[[ ${{ steps.generate_number.outputs.random_number}}==0]]; then exit 0; else exit 1; fi
      

    
